import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {apiPost, getNoteUri} from '../lib/api'
import { useRouter } from 'next/router'


function NewNote(){
  const router = useRouter()

  const submit = (ev)=>{
    ev.preventDefault()
    // let button = ev.target.elements.submit

    let name = ev.target.elements.name.value
    apiPost('/api/create',{name})
    .then(resp=>{
      let uri = getNoteUri(resp)
      router.push(uri)
    })

  }
  return (
    <div>
      <div>
        Create a new note : 
      </div>
      <div>
        <form onSubmit={submit}>
          <label>Note name : </label>
          <input type="text" name="name" />
          <input type="submit" value="create" />
        </form>
      </div>
    </div>
  )
}

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Next Note App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Welcome to Web-note</div>
        <div>
          You can easily create a shared-note for you and friends.

        </div>
        
        <NewNote />
      </main>

      <footer>
      </footer>
    </div>
  )
}
