import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {apiPost, getNoteUri} from '../lib/api'
import { useRouter } from 'next/router'
import React from 'react'


function NewNote(){
  const router = useRouter()
  const formRef = React.useRef()

  const submit = (ev)=>{
    ev.preventDefault()
    formRef.current.disabled = true
    let name = ev.target.elements.name.value
    apiPost('/api/create',{name})
    .then(resp=>{
      let uri = getNoteUri(resp)
      router.push(uri)
    })

  }


  return (
    <div className=" bg-white rounded-lg shadow-md py-4 px-4" >
      <div className="italic text-center">
        Create a new note : 
      </div>
      <div>
        <div>Note name : </div>
        <form className="flex " //border-2 border-gray-50 rounded-lg
          onSubmit={submit}>
          <input className=" bg-white border-b-2 border-gray-400 flex-1 focus:outline-none p-1 mr-4 "
             type="text" name="name" />
          <input  ref={formRef}  className=" bg-gray-200 py-1 px-1 rounded-lg cursor-pointer disabled:opacity-50"
            type="submit" value="create" />
        </form>
      </div>
    </div>
  )
}

export default function Home() {


  return (
    <div className=" h-screen flex flex-col">
      <Head>
        <title>Next Note App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <header className=" font-serif italic text-2xl py-6 text-center bg-blue-300   ">
        Web Note
      </header>
      <main className=" font-serif flex-1 bg-blue-50 p-4 ">

        <div className="py-4">
          <p>
            <span className=" font-bold">Web Note </span> 
            let's you easily create a shared note for you and friends.
            Start a house shopping list, organise meet-ups, 
            or keep tabs on anything else you need to coordinate.
          </p>

          <p>
            You need the link to access the note, 
            so make sure to save it and share it immediately 
            so you don't lose it.
          </p>

        </div>
        
        <NewNote />

      </main>

      <footer>
      </footer>
    </div>
  )
}
